# Generated by Django 4.2.20 on 2025-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_page',
            field=models.CharField(blank=True, help_text='Domyślna strona interfejsu użytkownika', max_length=100, null=True),
        ),
    ]
