# Generated by Django 4.2.20 on 2025-05-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_userprofile_default_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='authz.organizationalunit'),
        ),
    ]
