# Generated by Django 4.2.20 on 2025-04-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kontrahent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kontrahenta', models.CharField(max_length=255)),
                ('kontakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontrahenci', to='umowy.kontakt')),
            ],
        ),
        migrations.CreateModel(
            name='Umowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=100)),
                ('przedmiot', models.TextField()),
                ('data_zawarcia', models.DateField()),
                ('czy_wymaga_kontynuacji', models.BooleanField(default=False)),
                ('wymagana_data_zawarcia_kolejnej_umowy', models.DateField(blank=True, null=True)),
                ('czy_spelnia_wymagania_dora', models.BooleanField(default=False)),
                ('kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umowy', to='umowy.kontrahent')),
            ],
        ),
    ]
