# Generated by Django 4.2.20 on 2025-05-01 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_userprofile_default_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umowy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umowa',
            name='opiekun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prowadzone_umowy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='umowa',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umowy', to='authz.organizationalunit'),
        ),
    ]
