# Generated by Django 4.2.20 on 2025-05-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_userprofile_default_page'),
        ('umowy', '0002_umowa_opiekun_umowa_org_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrahent',
            old_name='nazwa_kontrahenta',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='umowa',
            old_name='czy_spelnia_wymagania_dora',
            new_name='czy_ramowa',
        ),
        migrations.RenameField(
            model_name='umowa',
            old_name='wymagana_data_zawarcia_kolejnej_umowy',
            new_name='wymagana_data_kontynuacji',
        ),
        migrations.RemoveField(
            model_name='umowa',
            name='data_zawarcia',
        ),
        migrations.RemoveField(
            model_name='umowa',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='umowa',
            name='przedmiot',
        ),
        migrations.AddField(
            model_name='umowa',
            name='czy_dotyczy_konkretnych_uslug',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='umowa',
            name='czy_spelnia_dora',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='umowa',
            name='jednostka_organizacyjna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authz.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='kontrahent',
            name='kontakt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.kontakt'),
        ),
        migrations.AlterField(
            model_name='umowa',
            name='kontrahent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowy.kontrahent'),
        ),
        migrations.CreateModel(
            name='ZmianaUmowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('umowa', 'Umowa'), ('aneks', 'Aneks'), ('porozumienie', 'Porozumienie'), ('inne', 'Inna zmiana')], max_length=20)),
                ('data_zawarcia', models.DateField()),
                ('data_obowiazywania_od', models.DateField()),
                ('data_obowiazywania_do', models.DateField(blank=True, null=True)),
                ('kwota_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('waluta', models.CharField(choices=[('PLN', 'Polski złoty'), ('EUR', 'Euro'), ('USD', 'Dolar amerykański')], default='PLN', max_length=10)),
                ('opis', models.TextField(blank=True)),
                ('umowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zmiany', to='umowy.umowa')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_zamowienia', models.CharField(max_length=100)),
                ('data_zlozenia', models.DateField()),
                ('data_realizacji', models.DateField(blank=True, null=True)),
                ('kwota_netto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waluta', models.CharField(choices=[('PLN', 'Polski złoty'), ('EUR', 'Euro'), ('USD', 'Dolar amerykański')], default='PLN', max_length=10)),
                ('opis', models.TextField(blank=True)),
                ('umowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='umowy.umowa')),
            ],
        ),
    ]
