# Generated by Django 4.2.20 on 2025-05-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0003_rename_nazwa_kontrahenta_kontrahent_nazwa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='producenci',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='przedmiot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='producenci',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='przedmiot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
