# Generated by Django 4.2.20 on 2025-05-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0004_zamowienie_producenci_zamowienie_przedmiot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlownikKategoriaUmowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SlownikKlasyfikacjaUmowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SlownikObszarFunkcjonalny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SlownikStatusUmowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlownikWlasciciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='data_podpisania',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='data_wypowiedzenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='finansowanie_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='numer_umowy_dostawcy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='trzeba_wypowiedziec',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zmianaumowy',
            name='producenci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.slownikkategoriaumowy'),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='klasyfikacja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.slownikklasyfikacjaumowy'),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='obszar_funkcjonalny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.slownikobszarfunkcjonalny'),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.slownikstatusumowy'),
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='wlasciciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.slownikwlasciciel'),
        ),
    ]
