# Generated by Django 4.2.20 on 2025-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0005_slownikkategoriaumowy_slownikklasyfikacjaumowy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zmianaumowy',
            name='obszar_funkcjonalny',
        ),
        migrations.AddField(
            model_name='zmianaumowy',
            name='obszary_funkcjonalne',
            field=models.ManyToManyField(blank=True, to='umowy.slownikobszarfunkcjonalny'),
        ),
    ]
